### ISSUE TITLE
Support specifying a download location for the SDK

### ISSUE THREAD

**Issue by rohanliston** [GoogleCloudPlatform/appengine-plugins#1007]
There doesn't appear to be a way to specify where the SDK will be downloaded to, which makes the SDK files more difficult to cache in a CI environment and prevent them from being downloaded/installed every time.

There is `tools.cloudSdkHome`, but the [documentation](https://cloud.google.com/appengine/docs/standard/java/gradle-reference) for that property indicates that the download will only occur if this property is unset:

> tools.cloudSdkHome: Optional property to configure the location of the Cloud SDK.
> If this property is not specified, then the plugin automatically downloads Cloud SDK.
> 

It would be great to perhaps have a secondary property to configure whether or not the SDK is downloaded to the specified path, e.g.

```
tools.cloudSdk.home=/path/to/sdk
tools.cloudSdk.downloadIfMissing=true
```

**Comment by suztomo** [comment]
If the plugin does not download gcloud command when it's missing, the plugin does not work. I think properly caching the `tools.cloudSdk.home=/path/to/sdk` would resolve your CI problem.

(Sorry I responded to a very old issue. I'll close this next week if there's no new findings)

**Comment by rohanliston** [comment]
@suztomo I'm no longer using App Engine or the CI platform in question anymore, so this issue is no longer relevant for me. Happy for you to close it if you wish, thanks.

**Comment by suztomo** [comment]
Thank you for your response.
