### ISSUE TITLE
Appengine plugins: Migrate GCR image to Artifact Registry

### ISSUE THREAD

**Issue by victor-denisenko** [GoogleCloudPlatform/appengine-plugins#1015]
Soon [Container Registry is deprecated](https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation).

As I understand [changes for building and deploying](https://cloud.google.com/artifact-registry/docs/transition/changes-gcp#workflow) **gcloud** need to use Artifact Registry repository path for the image, but I can't find a way to change this in the config.

Is any way to use Artifact Registry with this plugin? Or plans to support Artifact Registry?

**Comment by suztomo** [comment]
Thank you for report. We'll work on this. As per https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation, GCP projects that use Container Registry stops working March 2025 (next year).

**Comment by JoeWang1127** [comment]
Please refer to b/326385335 for the fix.

**Comment by Nikos-116** [comment]
Can you please explain what is b/326385335?
Any link?
Thanks
