### ISSUE TITLE
Explain how to use `extraFilesDirectories` in gradle

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/appengine-plugins#1026]
Hi! There seems to be something missing from the documentation. There's an `extraFilesDirectories` attribute in the gradle plugin but I can't figure out how we're supposed to use it?

My goal is to use the gradle `application` plugin-built `install` directory and startup script on GAE, without building a fat jar.

**Comment by stickfigure** [comment]
Looks like this was handled in maven-land already? https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/399

**Comment by lqiu96** [comment]
Hey, thanks for raising this. IIUC the above correctly it seems to be a gap in documentation between maven and gradle. We'll update the docs in the gradle plugin to include this (or possibly move these maven and gradle configs to a plugin-neutral place).

CC: @mpeddada1

**Comment by mpeddada1** [comment]
We have some documentation on the `extraFilesDirectory` for the app-gradle-plugin at https://github.com/GoogleCloudPlatform/appengine-plugins/blob/main/app-gradle-plugin/USER_GUIDE.md#stage-1 but it looks like it would beneficial to add more context as documented in https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#how-do-i-deploy-other-files-with-my-application-to-app-engine
