### ISSUE TITLE
[deploy] how to specify "no-cache" flag?

### ISSUE THREAD

**Issue by peterweb2005** [GoogleCloudPlatform/appengine-plugins#994]
as no-cache flag is required to solve the problem
https://stackoverflow.com/questions/77181996/gcloud-build-failure-error-failed-to-initialize-analyzer-no-such-object

## UPDATE
switch many configs, in order to run "gcloud app deploy --no-cache", but it only support java 8, 
and java 8 is not supported next month

**Comment by suztomo** [comment]
This seems to be resolved? I'll close this next week if that's the case.
