### ISSUE TITLE
What happened to com.google.cloud.tools:endpoints-framework-gradle-plugin?

### ISSUE THREAD

**Issue by TWiStErRob** [GoogleCloudPlatform/appengine-plugins#995]
Hi, sorry for asking here, but the other repository is archived:
https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin

however I don't see any deprecation or migration links like this repository has as the first line:
https://github.com/GoogleCloudPlatform/gradle-appengine-plugin

@suztomo could you unarchive and add a single line as to what happened?

If `apply plugin: 'com.google.cloud.tools.endpoints-framework-server'` is no longer a thing, and is deprecated, what is the replacement?

Note: the plugin is broken on Gradle 8, because the last [PR fix](https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/pull/109) never got released.

**Comment by dangazineu** [comment]
We don't intend to release further versions of the Endpoints Framework Gradle. Please fork and update the code if you would like to make any modifications, and reach out to Google Cloud Support with any further questions.

**Comment by TWiStErRob** [comment]
I can fork and add that readme line myself, but that doesn't help **your** users to find their way to the latest and greatest of the plethora of plugins you publish from different repositories.
